schema_version: 1

context:
  version: "0.56.1"

package:
  name: uharfbuzz
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/u/uharfbuzz/uharfbuzz-${{ version }}.tar.gz
  sha256: a0a6928ed66b166a931ebe5df9ac551b9c42983513030233dcd95b41fa827f97

build:
  number: 2
  script:
    - if: unix
      then:
        - rm -rf harfbuzz
        - export USE_SYSTEM_LIBS=1
    - if: win
      then:
        - del harfbuzz /s /q
        - set USE_SYSTEM_LIBS=1
    - pkg-config --exists harfbuzz-subset --debug
    - ${{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - cython
        - pkgconfig
    - pkg-config
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
  host:
    - pip
    - python
    - setuptools-scm
    - cython
    - pkgconfig
    - setuptools
    - harfbuzz
    # The following dependencies are needed for harfbuzz->freetype detection on windows
    - zlib
    - glib
  run:
    - python
  ignore_run_exports:
    from_package:
      - zlib
      - glib

tests:
  - python:
      imports:
        - uharfbuzz
      pip_check: true

about:
  summary: Streamlined Cython bindings for the harfbuzz shaping engine
  license: Apache-2.0
  license_file:
    - LICENSE
  homepage: https://github.com/trufont/uharfbuzz

extra:
  recipe-maintainers:
    - thewchan
    - jan-janssen
